language: python

python:
  -  '3.8'

install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install -r requirements.txt --use-feature=2020-resolver


script:
  - pytest